using EMS.API.Data;
using EMS.Shared.DTOs;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EMS.API.Features.Employees.Queries.GetPagedEmployees;

public class GetPagedEmployeesQueryHandler
    : IRequestHandler<
        GetPagedEmployeesQuery,
        PagedResultDto<EmployeeResponseDto>>
{
    private readonly AppDbContext _context;

    public GetPagedEmployeesQueryHandler(AppDbContext context)
    {
        _context = context;
    }

    public async Task<PagedResultDto<EmployeeResponseDto>> Handle(
        GetPagedEmployeesQuery request,
        CancellationToken cancellationToken)
    {
        // Use .Include(e => e.Department) if you want to ensure the relationship is loaded,
        // though the .Select() below will perform a JOIN automatically in the SQL generated by EF Core.
        var employees = _context.Employees.AsQueryable();

        if (!string.IsNullOrWhiteSpace(request.SearchText))
        {
            employees = employees.Where(e =>
                e.EmployeeName != null &&
                e.EmployeeName.Contains(request.SearchText));
        }

        switch (request.SortBy.ToLower())
        {
            case "latest":
                employees = employees
                    .OrderByDescending(e => e.CreatedDate);
                break;

            case "active":
                employees = employees
                    .OrderByDescending(e => e.IsActive);
                break;

            default:
                employees = employees
                    .OrderBy(e => e.Id);
                break;
        }

        var totalRecords = await employees
            .CountAsync(cancellationToken);

        var items = await employees
            .Skip((request.PageNumber - 1) * request.PageSize)
            .Take(request.PageSize)
            .Select(e => new EmployeeResponseDto
            {
                Id = e.Id,
                EmployeeName = e.EmployeeName,
                Description = e.Description,
                Salary = e.Salary,
                Email = e.Email,
                PhoneNumber = e.PhoneNumber,
                IsActive = e.IsActive,
                CreatedDate = e.CreatedDate,
                Latitude = e.Latitude,
                Longitude = e.Longitude,
                // Mapped the DepartmentName from the related Department entity
                DepartmentName = e.Department != null ? e.Department.Name : "N/A"
            })
            .ToListAsync(cancellationToken);

        return new PagedResultDto<EmployeeResponseDto>
        {
            Items = items,
            TotalRecords = totalRecords,
            PageNumber = request.PageNumber,
            PageSize = request.PageSize
        };
    }
}